### ISSUE TITLE
The config file is missing, or is it me?

### ISSUE THREAD

**Issue by PerfectCarl** [joshheyse/typescript-brunch#5]
When running the script 
```
brunch new https://github.com/joshheyse/typescript-brunch
brunch build
```
I got the following error
```
cran@cran-UX31E:~/Documents/Projects/web/white/brunch-w$ brunch build
/home/cran/npm/lib/node_modules/brunch/lib/helpers.js:585
      throw new Error("couldn\'t load config " + fullPath + ". " + error);
            ^
Error: couldn't load config /home/cran/Documents/Projects/web/white/brunch-w/config. Error: Cannot find module '/home/cran/Documents/Projects/web/white/brunch-w/config'
  at Object.exports.loadConfig (/home/cran/npm/lib/node_modules/brunch/lib/helpers.js:585:13)
  at Object.exports.loadConfig (/home/cran/npm/lib/node_modules/brunch/lib/helpers.js:583:22)
  at initialize (/home/cran/npm/lib/node_modules/brunch/lib/watch.js:460:18)
  at new BrunchWatcher (/home/cran/npm/lib/node_modules/brunch/lib/watch.js:649:5)
  at module.exports.watch (/home/cran/npm/lib/node_modules/brunch/lib/watch.js:708:10)
  at start (/home/cran/npm/lib/node_modules/brunch/lib/index.js:15:31)
  at Command.listener (/home/cran/npm/lib/node_modules/brunch/node_modules/commander/index.js:289:8)
  at Command.emit (events.js:110:17)
  at Command.parseArgs (/home/cran/npm/lib/node_modules/brunch/node_modules/commander/index.js:572:12)
  at Command.parse (/home/cran/npm/lib/node_modules/brunch/node_modules/commander/index.js:438:21)
  at Object.exports.run (/home/cran/npm/lib/node_modules/brunch/lib/cli.js:63:11)
  at Object.<anonymous> (/home/cran/npm/lib/node_modules/brunch/bin/brunch:11:22)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

```

**Comment by PerfectCarl** [comment]
Wait this is not a template, right?
